version: '3.7'

services:
  redis7001:
    image: redis:latest
    container_name: redis-7001
    command:
      ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./7001/conf/redis.conf:/etc/redis/redis.conf
      - ./7001/data:/data
    ports:
      - "7001:7001"
      - "17001:17001"
    restart: always
    network_mode: "host"
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10' 
        
  redis7002:
    image: redis:latest
    container_name: redis-7002
    command:
      ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./7002/conf/redis.conf:/etc/redis/redis.conf
      - ./7002/data:/data
    ports:
      - "7002:7002"
      - "17002:17002"
    restart: always
    network_mode: "host"
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    logging:
      options:
        max-size: '100m'
        max-file: '10'